name: Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/LICENSE'
      - '**/README.md'
      - '**/build.yml'
      - '**/.gitignore'
      - '**/.gitattributes'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5
      - uses: microsoft/setup-msbuild@v2

      - name: Nuget Restore
        run: nuget restore

      - name: Build .Net8
        run: msbuild /t:AssetStudio_GUI:publish /p:Configuration=Release /p:TargetFramework=net8.0-windows /p:SelfContained=false /verbosity:minimal

      - name: Build .Net8 CLI
        run: msbuild /t:AssetStudio_CLI:publish /p:Configuration=Release /p:TargetFramework=net8.0-windows /p:SelfContained=false /verbosity:minimal

      - name: Upload .Net8 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: net8.0-${{ github.sha }}
          path: AssetStudio.GUI/bin/Release/net8.0-windows/publish

      - name: Upload .Net8 CLI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: net8.0-${{ github.sha }}
          path: AssetStudio.GUI/bin/Release/net8.0-windows/publish
